import { z } from "zod";

/**
 * Every seed file is validated before a single row is written. Slovene
 * grammar is easy to get subtly wrong, and a malformed seed file that
 * silently half-imports is worse than one that refuses to import at all.
 */

export const partOfSpeechSchema = z.enum([
  "noun",
  "verb",
  "adjective",
  "adverb",
  "pronoun",
  "numeral",
  "preposition",
  "conjunction",
  "particle",
  "interjection",
  "phrase",
  "other",
]);

export const genderSchema = z.enum(["m", "f", "n"]);
export const aspectSchema = z.enum(["perfective", "imperfective", "biaspectual"]);
export const registerSchema = z.enum(["standard", "colloquial", "regional", "formal"]);
export const caseSchema = z.enum([
  "nominative",
  "accusative",
  "locative",
  "genitive",
  "dative",
  "instrumental",
]);
export const numberSchema = z.enum(["singular", "dual", "plural"]);
export const personSchema = z.enum(["first", "second", "third"]);
export const verbFormSchema = z.enum([
  "infinitive",
  "present",
  "past_participle",
  "imperative",
  "future",
  "conditional",
  "supine",
]);

// --- Frequency deck (generated by scripts/seed/build-deck.mjs) --------------

export const frequencyLexemeSchema = z.object({
  slovene: z.string().min(1),
  sloveneNormalized: z.string().min(1),
  german: z.array(z.string()),
  partOfSpeech: partOfSpeechSchema,
  gender: genderSchema.nullable(),
  aspect: aspectSchema.nullable(),
  frequencyRank: z.number().int().positive(),
  spokenFrequency: z.number().int().nonnegative(),
  writtenFrequency: z.number().int().nonnegative(),
  germanSource: z.string().nullable(),
  tags: z.array(z.string()),
});

export const frequencyLexemeFileSchema = z.object({
  version: z.number().int().positive(),
  generatedAt: z.string(),
  lexemes: z.array(frequencyLexemeSchema),
});

export const frequencyWordFormSchema = z.object({
  lemma: z.string().min(1),
  partOfSpeech: partOfSpeechSchema,
  form: z.string().min(1),
  formNormalized: z.string(),
  msd: z.string().nullable(),
  grammaticalCase: caseSchema.nullable(),
  number: numberSchema.nullable(),
  gender: genderSchema.nullable(),
  person: personSchema.nullable(),
  verbForm: verbFormSchema.nullable(),
  degree: z.string().nullable(),
  definiteness: z.string().nullable(),
});

export const frequencyWordFormFileSchema = z.object({
  version: z.number().int().positive(),
  generatedAt: z.string(),
  wordForms: z.array(frequencyWordFormSchema),
});

// --- Curriculum (hand-authored) --------------------------------------------

export const clozeSchema = z.object({
  /** Zero-based token index of the blank within the phrase. */
  position: z.number().int().nonnegative(),
  answer: z.string().min(1),
  hintDe: z.string().optional(),
  focusCase: caseSchema.optional(),
  focusNumber: numberSchema.optional(),
  focusVerbForm: verbFormSchema.optional(),
});

const baseItem = {
  slovene: z.string().min(1),
  tags: z.array(z.string()).default([]),
  register: registerSchema.default("standard"),
  regionLabel: z.string().optional(),
  difficulty: z.number().int().min(1).max(5).default(2),
  teachingNoteDe: z.string().optional(),
  notes: z.string().optional(),
};

export const lessonPhraseSchema = z.object({
  kind: z.literal("phrase"),
  ...baseItem,
  german: z.string().min(1),
  contextNote: z.string().optional(),
  cloze: z.array(clozeSchema).default([]),
});

export const lessonLexemeSchema = z.object({
  kind: z.literal("lexeme"),
  ...baseItem,
  german: z.array(z.string().min(1)).min(1),
  partOfSpeech: partOfSpeechSchema,
  gender: genderSchema.optional(),
  aspect: aspectSchema.optional(),
});

export const lessonItemSchema = z.discriminatedUnion("kind", [
  lessonPhraseSchema,
  lessonLexemeSchema,
]);

export const grammarNoteSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/),
  titleDe: z.string().min(1),
  bodyDe: z.string().min(1),
  tags: z.array(z.string()).default([]),
});

export const lessonSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/),
  titleDe: z.string().min(1),
  goalDe: z.string().optional(),
  introDe: z.string().optional(),
  position: z.number().int().positive(),
  estimatedMinutes: z.number().int().min(1).max(30).default(5),
  grammarNoteSlugs: z.array(z.string()).default([]),
  items: z.array(lessonItemSchema).min(1),
});

export const unitSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/),
  titleDe: z.string().min(1),
  descriptionDe: z.string().optional(),
  position: z.number().int().positive(),
});

export const curriculumFileSchema = z.object({
  unit: unitSchema,
  grammarNotes: z.array(grammarNoteSchema).default([]),
  lessons: z.array(lessonSchema).min(1),
});

export type CurriculumFile = z.infer<typeof curriculumFileSchema>;
export type LessonItem = z.infer<typeof lessonItemSchema>;
export type FrequencyLexeme = z.infer<typeof frequencyLexemeSchema>;
export type FrequencyWordForm = z.infer<typeof frequencyWordFormSchema>;

/**
 * Splits a phrase the way cloze positions count tokens: on whitespace, with
 * surrounding punctuation ignored. Shared by the importer and its tests so
 * "position 2" always means the same thing.
 */
export function tokenizePhrase(phrase: string): string[] {
  return phrase.split(/\s+/).filter(Boolean);
}

export function stripPunctuation(token: string): string {
  return token.replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "");
}

/** Lowercased, diacritics folded — the app's one normalisation rule. */
export function normalizeSlovene(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
}
